//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ArticleProjet.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Commande
    {
        public Commande()
        {
            this.LigneCommande = new HashSet<LigneCommande>();
        }
        public int num { get; set; }
        public System.DateTime dateCommande { get; set; }
        public virtual ICollection<LigneCommande> LigneCommande { get; set; }
    }
}