//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArticleProjet
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public int IdLigneCommande { get; set; }
        public string QuantiteCommande { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Article Article { get; set; }
    }
}
